server:
  port: 5001
  servlet:
    context-path: /sell
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sell?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hr
  jpa:
    show-sql: true
  application:
    name: product-service


  instance:
    instance-id: product-server-1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 #给服务端发送心跳 证明自己还活着间隔10s
    lease-expiration-duration-in-seconds: 30 #服务器接收最后一次心跳多少秒后将服务剔除
env:
  dev
